apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysub
  namespace: dg0312-lifesub-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysub
  template:
    metadata:
      labels:
        app: mysub
    spec:
      containers:
      - name: mysub
        image: acrdigitalgarage03.azurecr.io/dg0312/mysub:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: mysub-configmap
        - secretRef:
            name: mysub-secret
        - secretRef:
            name: common-secret
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
          limits:
            cpu: 1024m
            memory: 1024Mi
      imagePullSecrets:
      - name: acr-secret
